### DISCUSSION TITLE
Grafana tooltips

### DISCUSSION THREAD

**Discussion by gorlov** [gapitio/gapit-htmlgraphics-panel#67] [Q&A] [answered]
Is it possible, when hovering the mouse over an element, to show the tooltip by means of grafana, or should I write my own logic to display the tooltip?

**Comment by ZuperZee** [comment, marked as answer]
Well, it is possible. The panel doesn't have any script built in to show tooltips. Which means you have to build it yourself.

I made a little example on how it can be implemented. (Stole the code from [w3schools](https://www.w3schools.com/howto/howto_css_tooltip.asp) :D).

![tooltip-example](https://user-images.githubusercontent.com/39485579/146659323-db170b50-3916-4cb3-9320-3f3e10d241d8.gif)
 
`CSS`

```css
.tooltip {
  position: relative;
  display: inline-block;
  border-bottom: 1px dotted black;
}

.tooltip .tooltiptext {
  visibility: hidden;
  width: 120px;
  background-color: #333437;
  text-align: center;
  border-radius: 6px;
  padding: 5px 0;
  position: absolute;
  z-index: 1;
  bottom: 125%;
  left: 50%;
  margin-left: -60px;
  opacity: 0;
  transition: opacity 0.3s;
}

/* Arrow from the tooltip */
.tooltip .tooltiptext::after {
  content: "";
  position: absolute;
  top: 100%;
  left: 50%;
  margin-left: -5px;
  border-width: 5px;
  border-style: solid;
  border-color: #555 transparent transparent transparent;
}

.tooltip:hover .tooltiptext {
  visibility: visible;
  opacity: 1;
}
```

`HTML/SVG document`

```html
<div class="tooltip">
  <p id="htmlgraphics-value">Metric value</p>
  <span class="tooltiptext">Tooltip text</span>
</div>
```

`onRender` (Not needed. Only used to show some metric values.)

```js
// Sets the value from the first series on every refresh
const htmlgraphicsValue = htmlNode.getElementById('htmlgraphics-value');

if (htmlgraphicsValue) {
  const valueField = data.series[0]?.fields[1];
  if (valueField) {
    const length = valueField.values.length;
    htmlgraphicsValue.textContent = valueField.values.get(length - 1);
  } else {
    htmlgraphicsValue.textContent = "No data"
  }
}
```

`Panel options` (Import/export)

```json
{
    "calcsMutation": "standard",
    "reduceOptions": {
        "calcs": [
            "last"
        ]
    },
    "add100Percentage": false,
    "centerAlignContent": true,
    "overflow": "visible",
    "SVGBaseFix": true,
    "codeData": "{\n  \"text\": \"Random text\"\n}",
    "rootCSS": "",
    "css": ".tooltip {\n  position: relative;\n  display: inline-block;\n  border-bottom: 1px dotted black;\n}\n\n.tooltip .tooltiptext {\n  visibility: hidden;\n  width: 120px;\n  background-color: #333437;\n  text-align: center;\n  border-radius: 6px;\n  padding: 5px 0;\n  position: absolute;\n  z-index: 1;\n  bottom: 125%;\n  left: 50%;\n  margin-left: -60px;\n  opacity: 0;\n  transition: opacity 0.3s;\n}\n\n/* Arrow from the tooltip */\n.tooltip .tooltiptext::after {\n  content: \"\";\n  position: absolute;\n  top: 100%;\n  left: 50%;\n  margin-left: -5px;\n  border-width: 5px;\n  border-style: solid;\n  border-color: #555 transparent transparent transparent;\n}\n\n.tooltip:hover .tooltiptext {\n  visibility: visible;\n  opacity: 1;\n}",
    "html": "<div class=\"tooltip\">\n  <p id=\"htmlgraphics-value\">Metric value</p>\n  <span class=\"tooltiptext\">Tooltip text</span>\n</div>\n",
    "renderOnMount": true,
    "onRender": "// Sets the value from the first series on every refresh\nconst htmlgraphicsValue = htmlNode.getElementById('htmlgraphics-value');\n\nif (htmlgraphicsValue) {\n  const valueField = data.series[0]?.fields[1];\n  if (valueField) {\n    const length = valueField.values.length;\n    htmlgraphicsValue.textContent = valueField.values.get(length - 1);\n  } else {\n    htmlgraphicsValue.textContent = \"No data\"\n  }\n}\n",
    "dynamicData": false,
    "dynamicHtmlGraphics": false,
    "dynamicFieldDisplayValues": false,
    "dynamicProps": false,
    "panelupdateOnMount": true,
    "onInitOnResize": false,
    "onInit": ""
}
```
